# 워크플로우의 이름
name: News Crawling Bot

# 이 워크플로우가 언제 실행될지 결정
on:
  # 1. 스케줄에 따라 실행
  # UTC 기준 매일 22시 (한국 시간 오전 7시)에 실행
  schedule:
    - cron: '0 01 * * *'
  # 2. 수동으로 실행할 수 있도록 버튼 추가
  workflow_dispatch:

# 실제 실행될 작업 내용
jobs:
  build:
    # 실행될 환경
    runs-on: ubuntu-latest

    # 실행 단계
    steps:
      # 1. 저장소의 코드를 가져오는 단계
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 환경을 설정하는 단계
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 사용할 파이썬 버전

      # 3. 필요한 라이브러리(feedparser, requests)를 설치하는 단계
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. news_bot.py 파이썬 스크립트를 실행하는 단계
      - name: Run Python script
        # 여기서 GitHub Secrets에 저장된 SLACK_WEBHOOK_URL을 환경변수로 넘겨줌
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python news_bot.py
